package com.nxp.lpc8nxxnfcdemo.utils;

import android.os.Handler;

import com.nxp.lpc8nxxnfcdemo.activities.MainActivity;


public class LEDUtil {
    public static LEDUtil ledUtil= null;
    public static LEDUtil getInstance(){
            if (ledUtil==null){
                ledUtil= new LEDUtil();
            }
        return ledUtil;
    }
    int scrollLength;
    int FullScrollLength;
    boolean messageBuffer[][];
    boolean FullMessageBuffer[][];
    boolean singleSpace[]={false,false,false,false,false,false,false};
    int globali=0;
    boolean DisplayBuffer[][]= new boolean[25][7];
    int nextScrollTime=0;
    boolean isFirstTime=true;

    boolean[][][] lookup55 = {
        {{false,false,false,false,false,false,false,false}, {false,false,false,false,false,false,false,false}, {false,false,false,false,false,false,false,false}, {false,false,false,false,false,false,false,false}, {false,false,false,false,false,false,false,false}, {false,false,false,false,false,false,false,false}}, // SPACE
        {{false,false,false,false,false,false,false,false}, {false,false,false,false,false,false,false,false}, {false,false,true,false,true,true,true,false}, {false,false,false,false,false,false,false,false}, {false,false,false,false,false,false,false,false}, {false,false,false,false,false,false,false,false}}, // !
        {{false,false,false,false,false,false,false,false}, {false,false,false,false,false,true,true,false}, {false,false,false,false,false,false,false,false}, {false,false,false,false,false,true,true,false}, {false,false,false,false,false,false,false,false}, {false,false,false,false,false,false,false,false}}, // "
        {{false,false,false,true,false,true,false,false}, {false,false,true,true,true,true,true,false}, {false,false,false,true,false,true,false,false}, {false,false,true,true,true,true,true,false}, {false,false,false,true,false,true,false,false}, {false,false,false,false,false,false,false,false}}, // #
        {{false,false,true,false,true,true,false,false}, {false,false,true,false,true,false,true,false}, {false,false,true,true,true,true,true,false}, {false,false,true,false,true,false,true,false}, {false,false,false,true,true,false,true,false}, {false,false,false,false,false,false,false,false}}, // $
        {{false,false,true,false,false,false,true,false}, {false,false,false,true,false,false,false,false}, {false,false,false,false,true,false,false,false}, {false,false,false,false,false,true,false,false}, {false,false,true,false,false,false,true,false}, {false,false,false,false,false,false,false,false}}, // %
        {{false,false,false,true,true,false,false,false}, {false,false,true,false,false,true,false,false}, {false,false,true,false,true,false,true,false}, {false,false,true,true,false,true,true,false}, {false,false,true,true,false,false,false,false}, {false,false,false,false,false,false,false,false}}, // &
        {{false,false,false,false,false,false,false,false}, {false,false,false,false,false,false,false,false}, {false,false,false,false,false,true,false,false}, {false,false,false,false,false,false,true,false}, {false,false,false,false,false,false,false,false}, {false,false,false,false,false,false,false,false}}, // '
        {{false,false,false,false,false,false,false,false}, {false,false,false,false,false,false,false,false}, {false,false,false,true,true,true,false,false}, {false,false,true,false,false,false,true,false}, {false,false,false,false,false,false,false,false}, {false,false,false,false,false,false,false,false}}, // (
        {{false,false,false,false,false,false,false,false}, {false,false,false,false,false,false,false,false}, {false,false,true,false,false,false,true,false}, {false,false,false,true,true,true,false,false}, {false,false,false,false,false,false,false,false}, {false,false,false,false,false,false,false,false}}, // )
        {{false,false,false,false,false,false,false,false}, {false,false,true,false,true,false,true,false}, {false,false,false,true,true,true,false,false}, {false,false,false,true,true,true,false,false}, {false,false,true,false,true,false,true,false}, {false,false,false,false,false,false,false,false}}, // *
        {{false,false,false,false,true,false,false,false}, {false,false,false,false,true,false,false,false}, {false,false,true,true,true,true,true,false}, {false,false,false,false,true,false,false,false}, {false,false,false,false,true,false,false,false}, {false,false,false,false,false,false,false,false}}, // +
        {{false,false,false,false,false,false,false,false}, {false,false,false,false,false,false,false,false}, {false,false,true,false,false,false,false,false}, {false,false,false,true,false,false,false,false}, {false,false,false,false,false,false,false,false}, {false,false,false,false,false,false,false,false}}, // ,
        {{false,false,false,false,true,false,false,false}, {false,false,false,false,true,false,false,false}, {false,false,false,false,true,false,false,false}, {false,false,false,false,true,false,false,false}, {false,false,false,false,true,false,false,false}, {false,false,false,false,false,false,false,false}}, // -
        {{false,false,false,false,false,false,false,false}, {false,false,false,false,false,false,false,false}, {false,false,true,false,false,false,false,false}, {false,false,false,false,false,false,false,false}, {false,false,false,false,false,false,false,false}, {false,false,false,false,false,false,false,false}}, // .
        {{false,false,true,false,false,false,false,false}, {false,false,false,true,false,false,false,false}, {false,false,false,false,true,false,false,false}, {false,false,false,false,false,true,false,false}, {false,false,false,false,false,false,true,false}, {false,false,false,false,false,false,false,false}}, // /
        {{false,false,false,true,true,true,false,false}, {false,false,true,true,false,false,true,false}, {false,false,true,false,true,false,true,false}, {false,false,true,false,false,true,true,false}, {false,false,false,true,true,true,false,false}, {false,false,false,false,false,false,false,false}}, // 0,
        {{false,false,false,false,false,false,false,false}, {false,false,true,false,false,true,false,false}, {false,false,true,true,true,true,true,false}, {false,false,true,false,false,false,false,false}, {false,false,false,false,false,false,false,false}, {false,false,false,false,false,false,false,false}}, // 1,
        {{false,false,true,true,true,false,true,false}, {false,false,true,false,true,false,true,false}, {false,false,true,false,true,false,true,false}, {false,false,true,false,true,false,true,false}, {false,false,true,false,true,true,true,false}, {false,false,false,false,false,false,false,false}}, // 2
        {{false,false,true,false,false,false,true,false}, {false,false,true,false,false,false,true,false}, {false,false,true,false,true,false,true,false}, {false,false,true,false,true,false,true,false}, {false,false,true,true,true,true,true,false}, {false,false,false,false,false,false,false,false}}, // 3
        {{false,false,false,true,false,false,false,false}, {false,false,false,true,true,false,false,false}, {false,false,false,true,false,true,false,false}, {false,false,true,true,true,true,true,false}, {false,false,false,true,false,false,false,false}, {false,false,false,false,false,false,false,false}}, // 4
        {{false,false,true,false,true,true,true,false}, {false,false,true,false,true,false,true,false}, {false,false,true,false,true,false,true,false}, {false,false,true,false,true,false,true,false}, {false,false,false,true,false,false,true,false}, {false,false,false,false,false,false,false,false}}, // 5
        {{false,false,true,true,true,true,true,false}, {false,false,true,false,true,false,true,false}, {false,false,true,false,true,false,true,false}, {false,false,true,false,true,false,true,false}, {false,false,true,true,true,false,true,false}, {false,false,false,false,false,false,false,false}}, // 6
        {{false,false,false,false,false,false,true,false}, {false,false,false,false,false,false,true,false}, {false,false,true,true,false,false,true,false}, {false,false,false,false,true,false,true,false}, {false,false,false,false,false,true,true,false}, {false,false,false,false,false,false,false,false}}, // 7
        {{false,false,true,true,true,true,true,false}, {false,false,true,false,true,false,true,false}, {false,false,true,false,true,false,true,false}, {false,false,true,false,true,false,true,false}, {false,false,true,true,true,true,true,false}, {false,false,false,false,false,false,false,false}}, // 8
        {{false,false,true,false,true,true,true,false}, {false,false,true,false,true,false,true,false}, {false,false,true,false,true,false,true,false}, {false,false,true,false,true,false,true,false}, {false,false,true,true,true,true,true,false}, {false,false,false,false,false,false,false,false}}, // 9
        {{false,false,false,false,false,false,false,false}, {false,false,false,false,false,false,false,false}, {false,false,false,false,false,false,false,false}, {false,false,false,true,false,true,false,false}, {false,false,false,false,false,false,false,false}, {false,false,false,false,false,false,false,false}}, // :
        {{false,false,false,false,false,false,false,false}, {false,false,false,false,false,false,false,false}, {false,false,true,false,false,false,false,false}, {false,false,false,true,false,true,false,false}, {false,false,false,false,false,false,false,false}, {false,false,false,false,false,false,false,false}}, // ;
        {{false,false,false,false,false,false,false,false}, {false,false,false,false,true,false,false,false}, {false,false,false,true,false,true,false,false}, {false,false,true,false,false,false,true,false}, {false,false,false,false,false,false,false,false}, {false,false,false,false,false,false,false,false}}, // <
        {{false,false,false,false,false,false,false,false}, {false,false,false,true,false,true,false,false}, {false,false,false,true,false,true,false,false}, {false,false,false,true,false,true,false,false}, {false,false,false,true,false,true,false,false}, {false,false,false,false,false,false,false,false}}, // =
        {{false,false,false,false,false,false,false,false}, {false,false,true,false,false,false,true,false}, {false,false,false,true,false,true,false,false}, {false,false,false,false,true,false,false,false}, {false,false,false,false,false,false,false,false}, {false,false,false,false,false,false,false,false}}, // >
        {{false,false,false,false,false,false,false,false}, {false,false,false,false,false,true,false,false}, {false,false,false,false,false,false,true,false}, {false,false,true,false,true,false,true,false}, {false,false,false,false,false,true,false,false}, {false,false,false,false,false,false,false,false}}, // ?
        {{false,false,true,true,true,true,true,false}, {false,false,true,false,false,false,true,false}, {false,false,true,false,false,false,true,false}, {false,false,true,false,true,false,true,false}, {false,false,true,false,true,true,true,false}, {false,false,false,false,false,false,false,false}}, // @
        {{false,false,true,true,true,false,false,false}, {false,false,false,true,false,true,false,false}, {false,false,false,true,false,false,true,false}, {false,false,false,true,false,true,false,false}, {false,false,true,true,true,false,false,false}, {false,false,false,false,false,false,false,false}}, // A
        {{false,false,true,true,true,true,true,false}, {false,false,true,false,true,false,true,false}, {false,false,true,false,true,false,true,false}, {false,false,true,false,true,false,true,false}, {false,false,false,true,false,true,false,false}, {false,false,false,false,false,false,false,false}}, // B
        {{false,false,false,true,true,true,false,false}, {false,false,true,false,false,false,true,false}, {false,false,true,false,false,false,true,false}, {false,false,true,false,false,false,true,false}, {false,false,false,true,false,true,false,false}, {false,false,false,false,false,false,false,false}}, // C
        {{false,false,true,true,true,true,true,false}, {false,false,true,false,false,false,true,false}, {false,false,true,false,false,false,true,false}, {false,false,true,false,false,false,true,false}, {false,false,false,true,true,true,false,false}, {false,false,false,false,false,false,false,false}}, // D
        {{false,false,true,true,true,true,true,false}, {false,false,true,false,true,false,true,false}, {false,false,true,false,true,false,true,false}, {false,false,true,false,false,false,true,false}, {false,false,true,false,false,false,true,false}, {false,false,false,false,false,false,false,false}}, // E
        {{false,false,true,true,true,true,true,false}, {false,false,false,false,true,false,true,false}, {false,false,false,false,true,false,true,false}, {false,false,false,false,false,false,true,false}, {false,false,false,false,false,false,true,false}, {false,false,false,false,false,false,false,false}}, // F
        {{false,false,false,true,true,true,false,false}, {false,false,true,false,false,false,true,false}, {false,false,true,false,false,false,true,false}, {false,false,true,false,true,false,true,false}, {false,false,false,true,true,false,false,false}, {false,false,false,false,false,false,false,false}}, // G
        {{false,false,true,true,true,true,true,false}, {false,false,false,false,true,false,false,false}, {false,false,false,false,true,false,false,false}, {false,false,false,false,true,false,false,false}, {false,false,true,true,true,true,true,false}, {false,false,false,false,false,false,false,false}}, // H
        {{false,false,false,false,false,false,false,false}, {false,false,true,false,false,false,true,false}, {false,false,true,true,true,true,true,false}, {false,false,true,false,false,false,true,false}, {false,false,false,false,false,false,false,false}, {false,false,false,false,false,false,false,false}}, // I
        {{false,false,false,true,false,false,true,false}, {false,false,true,false,false,false,true,false}, {false,false,true,false,false,false,true,false}, {false,false,false,true,true,true,true,false}, {false,false,false,false,false,false,true,false}, {false,false,false,false,false,false,false,false}}, // J
        {{false,false,true,true,true,true,true,false}, {false,false,false,false,true,false,false,false}, {false,false,false,false,true,true,false,false}, {false,false,false,true,false,true,false,false}, {false,false,true,false,false,false,true,false}, {false,false,false,false,false,false,false,false}}, // K
        {{false,false,true,true,true,true,true,false}, {false,false,true,false,false,false,false,false}, {false,false,true,false,false,false,false,false}, {false,false,true,false,false,false,false,false}, {false,false,true,false,false,false,false,false}, {false,false,false,false,false,false,false,false}}, // L
        {{false,false,true,true,true,true,true,false}, {false,false,false,false,false,true,false,false}, {false,false,false,false,true,false,false,false}, {false,false,false,false,false,true,false,false}, {false,false,true,true,true,true,true,false}, {false,false,false,false,false,false,false,false}}, // M
        {{false,false,true,true,true,true,true,false}, {false,false,false,false,false,true,false,false}, {false,false,false,false,true,false,false,false}, {false,false,false,true,false,false,false,false}, {false,false,true,true,true,true,true,false}, {false,false,false,false,false,false,false,false}}, // N
        {{false,false,false,true,true,true,false,false}, {false,false,true,false,false,false,true,false}, {false,false,true,false,false,false,true,false}, {false,false,true,false,false,false,true,false}, {false,false,false,true,true,true,false,false}, {false,false,false,false,false,false,false,false}}, // O
        {{false,false,true,true,true,true,true,false}, {false,false,false,false,true,false,true,false}, {false,false,false,false,true,false,true,false}, {false,false,false,false,true,false,true,false}, {false,false,false,false,false,true,false,false}, {false,false,false,false,false,false,false,false}}, // P
        {{false,false,false,true,true,true,false,false}, {false,false,true,false,false,false,true,false}, {false,false,true,false,true,false,true,false}, {false,false,false,true,false,false,true,false}, {false,false,true,false,true,true,false,false}, {false,false,false,false,false,false,false,false}}, // Q
        {{false,false,true,true,true,true,true,false}, {false,false,false,false,true,false,true,false}, {false,false,false,false,true,false,true,false}, {false,false,false,true,true,false,true,false}, {false,false,true,false,true,true,false,false}, {false,false,false,false,false,false,false,false}}, // R
        {{false,false,true,false,false,true,false,false}, {false,false,true,false,true,false,true,false}, {false,false,true,false,true,false,true,false}, {false,false,true,false,true,false,true,false}, {false,false,false,true,false,false,true,false}, {false,false,false,false,false,false,false,false}}, // S
        {{false,false,false,false,false,false,true,false}, {false,false,false,false,false,false,true,false}, {false,false,true,true,true,true,true,false}, {false,false,false,false,false,false,true,false}, {false,false,false,false,false,false,true,false}, {false,false,false,false,false,false,false,false}}, // T
        {{false,false,false,true,true,true,true,false}, {false,false,true,false,false,false,false,false}, {false,false,true,false,false,false,false,false}, {false,false,true,false,false,false,false,false}, {false,false,false,true,true,true,true,false}, {false,false,false,false,false,false,false,false}}, // U
        {{false,false,false,false,false,false,true,false}, {false,false,false,false,true,true,false,false}, {false,false,true,true,false,false,false,false}, {false,false,false,false,true,true,false,false}, {false,false,false,false,false,false,true,false}, {false,false,false,false,false,false,false,false}}, // V
        {{false,false,true,true,true,true,true,false}, {false,false,false,true,false,false,false,false}, {false,false,false,false,true,false,false,false}, {false,false,false,true,false,false,false,false}, {false,false,true,true,true,true,true,false}, {false,false,false,false,false,false,false,false}}, // W
        {{false,false,true,false,false,false,true,false}, {false,false,false,true,false,true,false,false}, {false,false,false,false,true,false,false,false}, {false,false,false,true,false,true,false,false}, {false,false,true,false,false,false,true,false}, {false,false,false,false,false,false,false,false}}, // X
        {{false,false,false,false,false,false,true,false}, {false,false,false,false,false,true,false,false}, {false,false,true,true,true,false,false,false}, {false,false,false,false,false,true,false,false}, {false,false,false,false,false,false,true,false}, {false,false,false,false,false,false,false,false}}, // Y
        {{false,false,true,false,false,false,true,false}, {false,false,true,true,false,false,true,false}, {false,false,true,false,true,false,true,false}, {false,false,true,false,false,true,true,false}, {false,false,true,false,false,false,true,false}, {false,false,false,false,false,false,false,false}}, // Z
        {{false,false,false,false,false,false,false,false}, {false,false,true,true,true,true,true,false}, {false,false,true,false,false,false,true,false}, {false,false,true,false,false,false,true,false}, {false,false,false,false,false,false,false,false}, {false,false,false,false,false,false,false,false}}, // [
        {{false,false,false,false,false,false,true,false}, {false,false,false,false,false,true,false,false}, {false,false,false,false,true,false,false,false}, {false,false,false,true,false,false,false,false}, {false,false,true,false,false,false,false,false}, {false,false,false,false,false,false,false,false}}, // \
        {{false,false,false,false,false,false,false,false}, {false,false,false,false,false,false,false,false}, {false,false,true,false,false,false,true,false}, {false,false,true,false,false,false,true,false}, {false,false,true,true,true,true,true,false}, {false,false,false,false,false,false,false,false}}, // ]
        {{false,false,false,false,true,false,false,false}, {false,false,false,false,false,true,false,false}, {false,false,false,false,false,false,true,false}, {false,false,false,false,false,true,false,false}, {false,false,false,false,true,false,false,false}, {false,false,false,false,false,false,false,false}}, // ^
        {{false,false,true,false,false,false,false,false}, {false,false,true,false,false,false,false,false}, {false,false,true,false,false,false,false,false}, {false,false,true,false,false,false,false,false}, {false,false,true,false,false,false,false,false}, {false,false,false,false,false,false,false,false}}, // _
        {{false,false,false,false,false,false,false,false}, {false,false,false,false,false,false,false,false}, {false,false,false,false,false,false,true,false}, {false,false,false,false,false,true,false,false}, {false,false,false,false,false,false,false,false}, {false,false,false,false,false,false,false,false}}, // `
        {{false,false,true,true,true,false,false,false}, {false,false,false,true,false,true,false,false}, {false,false,false,true,false,false,true,false}, {false,false,false,true,false,true,false,false}, {false,false,true,true,true,false,false,false}, {false,false,false,false,false,false,false,false}}, // A
        {{false,false,true,true,true,true,true,false}, {false,false,true,false,true,false,true,false}, {false,false,true,false,true,false,true,false}, {false,false,true,false,true,false,true,false}, {false,false,false,true,false,true,false,false}, {false,false,false,false,false,false,false,false}}, // B
        {{false,false,false,true,true,true,false,false}, {false,false,true,false,false,false,true,false}, {false,false,true,false,false,false,true,false}, {false,false,true,false,false,false,true,false}, {false,false,false,true,false,true,false,false}, {false,false,false,false,false,false,false,false}}, // C
        {{false,false,true,true,true,true,true,false}, {false,false,true,false,false,false,true,false}, {false,false,true,false,false,false,true,false}, {false,false,true,false,false,false,true,false}, {false,false,false,true,true,true,false,false}, {false,false,false,false,false,false,false,false}}, // D
        {{false,false,true,true,true,true,true,false}, {false,false,true,false,true,false,true,false}, {false,false,true,false,true,false,true,false}, {false,false,true,false,false,false,true,false}, {false,false,true,false,false,false,true,false}, {false,false,false,false,false,false,false,false}}, // E
        {{false,false,true,true,true,true,true,false}, {false,false,false,false,true,false,true,false}, {false,false,false,false,true,false,true,false}, {false,false,false,false,false,false,true,false}, {false,false,false,false,false,false,true,false}, {false,false,false,false,false,false,false,false}}, // F
        {{false,false,false,true,true,true,false,false}, {false,false,true,false,false,false,true,false}, {false,false,true,false,false,false,true,false}, {false,false,true,false,true,false,true,false}, {false,false,false,true,true,false,false,false}, {false,false,false,false,false,false,false,false}}, // G
        {{false,false,true,true,true,true,true,false}, {false,false,false,false,true,false,false,false}, {false,false,false,false,true,false,false,false}, {false,false,false,false,true,false,false,false}, {false,false,true,true,true,true,true,false}, {false,false,false,false,false,false,false,false}}, // H
        {{false,false,false,false,false,false,false,false}, {false,false,true,false,false,false,true,false}, {false,false,true,true,true,true,true,false}, {false,false,true,false,false,false,true,false}, {false,false,false,false,false,false,false,false}, {false,false,false,false,false,false,false,false}}, // I
        {{false,false,false,true,false,false,true,false}, {false,false,true,false,false,false,true,false}, {false,false,true,false,false,false,true,false}, {false,false,false,true,true,true,true,false}, {false,false,false,false,false,false,true,false}, {false,false,false,false,false,false,false,false}}, // J
        {{false,false,true,true,true,true,true,false}, {false,false,false,false,true,false,false,false}, {false,false,false,false,true,true,false,false}, {false,false,false,true,false,true,false,false}, {false,false,true,false,false,false,true,false}, {false,false,false,false,false,false,false,false}}, // K
        {{false,false,true,true,true,true,true,false}, {false,false,true,false,false,false,false,false}, {false,false,true,false,false,false,false,false}, {false,false,true,false,false,false,false,false}, {false,false,true,false,false,false,false,false}, {false,false,false,false,false,false,false,false}}, // L
        {{false,false,true,true,true,true,true,false}, {false,false,false,false,false,true,false,false}, {false,false,false,false,true,false,false,false}, {false,false,false,false,false,true,false,false}, {false,false,true,true,true,true,true,false}, {false,false,false,false,false,false,false,false}}, // M
        {{false,false,true,true,true,true,true,false}, {false,false,false,false,false,true,false,false}, {false,false,false,false,true,false,false,false}, {false,false,false,true,false,false,false,false}, {false,false,true,true,true,true,true,false}, {false,false,false,false,false,false,false,false}}, // N
        {{false,false,false,true,true,true,false,false}, {false,false,true,false,false,false,true,false}, {false,false,true,false,false,false,true,false}, {false,false,true,false,false,false,true,false}, {false,false,false,true,true,true,false,false}, {false,false,false,false,false,false,false,false}}, // O
        {{false,false,true,true,true,true,true,false}, {false,false,false,false,true,false,true,false}, {false,false,false,false,true,false,true,false}, {false,false,false,false,true,false,true,false}, {false,false,false,false,false,true,false,false}, {false,false,false,false,false,false,false,false}}, // P
        {{false,false,false,true,true,true,false,false}, {false,false,true,false,false,false,true,false}, {false,false,true,false,true,false,true,false}, {false,false,false,true,false,false,true,false}, {false,false,true,false,true,true,false,false}, {false,false,false,false,false,false,false,false}}, // Q
        {{false,false,true,true,true,true,true,false}, {false,false,false,false,true,false,true,false}, {false,false,false,false,true,false,true,false}, {false,false,false,true,true,false,true,false}, {false,false,true,false,true,true,false,false}, {false,false,false,false,false,false,false,false}}, // R
        {{false,false,true,false,false,true,false,false}, {false,false,true,false,true,false,true,false}, {false,false,true,false,true,false,true,false}, {false,false,true,false,true,false,true,false}, {false,false,false,true,false,false,true,false}, {false,false,false,false,false,false,false,false}}, // S
        {{false,false,false,false,false,false,true,false}, {false,false,false,false,false,false,true,false}, {false,false,true,true,true,true,true,false}, {false,false,false,false,false,false,true,false}, {false,false,false,false,false,false,true,false}, {false,false,false,false,false,false,false,false}}, // T
        {{false,false,false,true,true,true,true,false}, {false,false,true,false,false,false,false,false}, {false,false,true,false,false,false,false,false}, {false,false,true,false,false,false,false,false}, {false,false,false,true,true,true,true,false}, {false,false,false,false,false,false,false,false}}, // U
        {{false,false,false,false,false,false,true,false}, {false,false,false,false,true,true,false,false}, {false,false,true,true,false,false,false,false}, {false,false,false,false,true,true,false,false}, {false,false,false,false,false,false,true,false}, {false,false,false,false,false,false,false,false}}, // V
        {{false,false,true,true,true,true,true,false}, {false,false,false,true,false,false,false,false}, {false,false,false,false,true,false,false,false}, {false,false,false,true,false,false,false,false}, {false,false,true,true,true,true,true,false}, {false,false,false,false,false,false,false,false}}, // W
        {{false,false,true,false,false,false,true,false}, {false,false,false,true,false,true,false,false}, {false,false,false,false,true,false,false,false}, {false,false,false,true,false,true,false,false}, {false,false,true,false,false,false,true,false}, {false,false,false,false,false,false,false,false}}, // X
        {{false,false,false,false,false,false,true,false}, {false,false,false,false,false,true,false,false}, {false,false,true,true,true,false,false,false}, {false,false,false,false,false,true,false,false}, {false,false,false,false,false,false,true,false}, {false,false,false,false,false,false,false,false}}, // Y
        {{false,false,true,false,false,false,true,false}, {false,false,true,true,false,false,true,false}, {false,false,true,false,true,false,true,false}, {false,false,true,false,false,true,true,false}, {false,false,true,false,false,false,true,false}, {false,false,false,false,false,false,false,false}}, // Z
        {{false,false,false,false,false,false,false,false}, {false,false,false,false,false,false,false,false}, {false,false,false,false,false,false,false,false}, {false,false,false,false,false,false,false,false}, {false,false,false,false,false,false,false,false}, {false,false,false,false,false,false,false,false}},
        {{false,false,false,false,false,false,false,false}, {false,false,false,false,false,false,false,false}, {false,false,false,false,false,false,false,false}, {false,false,false,false,false,false,false,false}, {false,false,false,false,false,false,false,false}, {false,false,false,false,false,false,false,false}},
        {{false,false,false,false,false,false,false,false}, {false,false,false,false,false,false,false,false}, {false,false,false,false,false,false,false,false}, {false,false,false,false,false,false,false,false}, {false,false,false,false,false,false,false,false}, {false,false,false,false,false,false,false,false}},
        {{false,false,false,false,false,false,false,false}, {false,false,false,false,false,false,false,false}, {false,false,false,false,false,false,false,false}, {false,false,false,false,false,false,false,false}, {false,false,false,false,false,false,false,false}, {false,false,false,false,false,false,false,false}},
        {{false,false,false,false,false,false,false,false}, {false,false,false,false,false,false,false,false}, {false,false,false,false,false,false,false,false}, {false,false,false,false,false,false,false,false}, {false,false,false,false,false,false,false,false}, {false,false,false,false,false,false,false,false}}
    };


    boolean[][][] lookup57 ={
            {{false,false,false,false,false,false,false,false}, {false,false,false,false,false,false,false,false}, {false,false,false,false,false,false,false,false}, {false,false,false,false,false,false,false,false}, {false,false,false,false,false,false,false,false},{false,false,false,false,false,false,false,false}},// (space)
            {{false,false,false,false,false,false,false,false}, {false,false,false,false,false,false,false,false}, {false,true,false,true,true,true,true,true}, {false,false,false,false,false,false,false,false}, {false,false,false,false,false,false,false,false},{false,false,false,false,false,false,false,false}},// !
            {{false,false,false,false,false,false,false,false}, {false,false,false,false,false,true,true,true}, {false,false,false,false,false,false,false,false}, {false,false,false,false,false,true,true,true}, {false,false,false,false,false,false,false,false},{false,false,false,false,false,false,false,false}},// "
            {{false,false,false,true,false,true,false,false}, {false,true,true,true,true,true,true,true}, {false,false,false,true,false,true,false,false}, {false,true,true,true,true,true,true,true}, {false,false,false,true,false,true,false,false},{false,false,false,false,false,false,false,false}},// #
            {{false,false,true,false,false,true,false,false}, {false,false,true,false,true,false,true,false}, {false,true,true,true,true,true,true,true}, {false,false,true,false,true,false,true,false}, {false,false,false,true,false,false,true,false},{false,false,false,false,false,false,false,false}},// $
            {{false,false,true,false,false,false,true,true}, {false,false,false,true,false,false,true,true}, {false,false,false,false,true,false,false,false}, {false,true,true,false,false,true,false,false}, {false,true,true,false,false,false,true,false},{false,false,false,false,false,false,false,false}},// %
            {{false,false,true,true,false,true,true,false}, {false,true,false,false,true,false,false,true}, {false,true,false,true,false,true,false,true}, {false,false,true,false,false,false,true,false}, {false,true,false,true,false,false,false,false},{false,false,false,false,false,false,false,false}},// &
            {{false,false,false,false,false,false,false,false}, {false,false,false,false,false,true,false,true}, {false,false,false,false,false,false,true,true}, {false,false,false,false,false,false,false,false}, {false,false,false,false,false,false,false,false},{false,false,false,false,false,false,false,false}},// '
            {{false,false,false,false,false,false,false,false}, {false,false,false,true,true,true,false,false}, {false,false,true,false,false,false,true,false}, {false,true,false,false,false,false,false,true}, {false,false,false,false,false,false,false,false},{false,false,false,false,false,false,false,false}},// (
            {{false,false,false,false,false,false,false,false}, {false,true,false,false,false,false,false,true}, {false,false,true,false,false,false,true,false}, {false,false,false,true,true,true,false,false}, {false,false,false,false,false,false,false,false},{false,false,false,false,false,false,false,false}},// )
            {{false,false,false,false,true,false,false,false}, {false,false,true,false,true,false,true,false}, {false,false,false,true,true,true,false,false}, {false,false,true,false,true,false,true,false}, {false,false,false,false,true,false,false,false},{false,false,false,false,false,false,false,false}},// *
            {{false,false,false,false,true,false,false,false}, {false,false,false,false,true,false,false,false}, {false,false,true,true,true,true,true,false}, {false,false,false,false,true,false,false,false}, {false,false,false,false,true,false,false,false},{false,false,false,false,false,false,false,false}},// +
            {{false,false,false,false,false,false,false,false}, {false,true,false,true,false,false,false,false}, {false,false,true,true,false,false,false,false}, {false,false,false,false,false,false,false,false}, {false,false,false,false,false,false,false,false},{false,false,false,false,false,false,false,false}},// ,
            {{false,false,false,false,true,false,false,false}, {false,false,false,false,true,false,false,false}, {false,false,false,false,true,false,false,false}, {false,false,false,false,true,false,false,false}, {false,false,false,false,true,false,false,false},{false,false,false,false,false,false,false,false}},// -
            {{false,false,false,false,false,false,false,false}, {false,true,true,false,false,false,false,false}, {false,true,true,false,false,false,false,false}, {false,false,false,false,false,false,false,false}, {false,false,false,false,false,false,false,false},{false,false,false,false,false,false,false,false}},// .
            {{false,false,true,false,false,false,false,false}, {false,false,false,true,false,false,false,false}, {false,false,false,false,true,false,false,false}, {false,false,false,false,false,true,false,false}, {false,false,false,false,false,false,true,false},{false,false,false,false,false,false,false,false}},// /
            {{false,false,true,true,true,true,true,false}, {false,true,false,true,false,false,false,true}, {false,true,false,false,true,false,false,true}, {false,true,false,false,false,true,false,true}, {false,false,true,true,true,true,true,false},{false,false,false,false,false,false,false,false}},//{{false,
            {{false,false,false,false,false,false,false,false}, {false,true,false,false,false,false,true,false}, {false,true,true,true,true,true,true,true}, {false,true,false,false,false,false,false,false}, {false,false,false,false,false,false,false,false},{false,false,false,false,false,false,false,false}},// true,
            {{false,true,false,false,false,false,true,false}, {false,true,true,false,false,false,false,true}, {false,true,false,true,false,false,false,true}, {false,true,false,false,true,false,false,true}, {false,true,false,false,false,true,true,false},{false,false,false,false,false,false,false,false}},// 2
            {{false,false,true,false,false,false,false,true}, {false,true,false,false,false,false,false,true}, {false,true,false,false,false,true,false,true}, {false,true,false,false,true,false,true,true}, {false,false,true,true,false,false,false,true},{false,false,false,false,false,false,false,false}},// 3
            {{false,false,false,true,true,false,false,false}, {false,false,false,true,false,true,false,false}, {false,false,false,true,false,false,true,false}, {false,true,true,true,true,true,true,true}, {false,false,false,true,false,false,false,false},{false,false,false,false,false,false,false,false}},// 4
            {{false,false,true,false,false,true,true,true}, {false,true,false,false,false,true,false,true}, {false,true,false,false,false,true,false,true}, {false,true,false,false,false,true,false,true}, {false,false,true,true,true,false,false,true},{false,false,false,false,false,false,false,false}},// 5
            {{false,false,true,true,true,true,false,false}, {false,true,false,false,true,false,true,false}, {false,true,false,false,true,false,false,true}, {false,true,false,false,true,false,false,true}, {false,false,true,true,false,false,false,false},{false,false,false,false,false,false,false,false}},// 6
            {{false,false,false,false,false,false,false,true}, {false,true,true,true,false,false,false,true}, {false,false,false,false,true,false,false,true}, {false,false,false,false,false,true,false,true}, {false,false,false,false,false,false,true,true},{false,false,false,false,false,false,false,false}},// 7
            {{false,false,true,true,false,true,true,false}, {false,true,false,false,true,false,false,true}, {false,true,false,false,true,false,false,true}, {false,true,false,false,true,false,false,true}, {false,false,true,true,false,true,true,false},{false,false,false,false,false,false,false,false}},// 8
            {{false,false,false,false,false,true,true,false}, {false,true,false,false,true,false,false,true}, {false,true,false,false,true,false,false,true}, {false,false,true,false,true,false,false,true}, {false,false,false,true,true,true,true,false},{false,false,false,false,false,false,false,false}},// 9
            {{false,false,false,false,false,false,false,false}, {false,false,true,true,false,true,true,false}, {false,false,true,true,false,true,true,false}, {false,false,false,false,false,false,false,false}, {false,false,false,false,false,false,false,false},{false,false,false,false,false,false,false,false}},// :
            {{false,false,false,false,false,false,false,false}, {false,true,false,true,false,true,true,false}, {false,false,true,true,false,true,true,false}, {false,false,false,false,false,false,false,false}, {false,false,false,false,false,false,false,false},{false,false,false,false,false,false,false,false}},// ;
            {{false,false,false,false,false,false,false,false}, {false,false,false,false,true,false,false,false}, {false,false,false,true,false,true,false,false}, {false,false,true,false,false,false,true,false}, {false,true,false,false,false,false,false,true},{false,false,false,false,false,false,false,false}},// <
            {{false,false,false,true,false,true,false,false}, {false,false,false,true,false,true,false,false}, {false,false,false,true,false,true,false,false}, {false,false,false,true,false,true,false,false}, {false,false,false,true,false,true,false,false},{false,false,false,false,false,false,false,false}},// =
            {{false,true,false,false,false,false,false,true}, {false,false,true,false,false,false,true,false}, {false,false,false,true,false,true,false,false}, {false,false,false,false,true,false,false,false}, {false,false,false,false,false,false,false,false},{false,false,false,false,false,false,false,false}},// >
            {{false,false,false,false,false,false,true,false}, {false,false,false,false,false,false,false,true}, {false,true,false,true,false,false,false,true}, {false,false,false,false,true,false,false,true}, {false,false,false,false,false,true,true,false},{false,false,false,false,false,false,false,false}},// ?
            {{false,false,true,true,false,false,true,false}, {false,true,false,false,true,false,false,true}, {false,true,true,true,true,false,false,true}, {false,true,false,false,false,false,false,true}, {false,false,true,true,true,true,true,false},{false,false,false,false,false,false,false,false}},// @
            {{false,true,true,true,true,true,true,false}, {false,false,false,true,false,false,false,true}, {false,false,false,true,false,false,false,true}, {false,false,false,true,false,false,false,true}, {false,true,true,true,true,true,true,false},{false,false,false,false,false,false,false,false}},// A
            {{false,true,true,true,true,true,true,true}, {false,true,false,false,true,false,false,true}, {false,true,false,false,true,false,false,true}, {false,true,false,false,true,false,false,true}, {false,false,true,true,false,true,true,false},{false,false,false,false,false,false,false,false}},// B
            {{false,false,true,true,true,true,true,false}, {false,true,false,false,false,false,false,true}, {false,true,false,false,false,false,false,true}, {false,true,false,false,false,false,false,true}, {false,false,true,false,false,false,true,false},{false,false,false,false,false,false,false,false}},// C
            {{false,true,true,true,true,true,true,true}, {false,true,false,false,false,false,false,true}, {false,true,false,false,false,false,false,true}, {false,false,true,false,false,false,true,false}, {false,false,false,true,true,true,false,false},{false,false,false,false,false,false,false,false}},// D
            {{false,true,true,true,true,true,true,true}, {false,true,false,false,true,false,false,true}, {false,true,false,false,true,false,false,true}, {false,true,false,false,true,false,false,true}, {false,true,false,false,false,false,false,true},{false,false,false,false,false,false,false,false}},// E
            {{false,true,true,true,true,true,true,true}, {false,false,false,false,true,false,false,true}, {false,false,false,false,true,false,false,true}, {false,false,false,false,false,false,false,true}, {false,false,false,false,false,false,false,true},{false,false,false,false,false,false,false,false}},// F
            {{false,false,true,true,true,true,true,false}, {false,true,false,false,false,false,false,true}, {false,true,false,false,false,false,false,true}, {false,true,false,true,false,false,false,true}, {false,false,true,true,false,false,true,false},{false,false,false,false,false,false,false,false}},// G
            {{false,true,true,true,true,true,true,true}, {false,false,false,false,true,false,false,false}, {false,false,false,false,true,false,false,false}, {false,false,false,false,true,false,false,false}, {false,true,true,true,true,true,true,true},{false,false,false,false,false,false,false,false}},// H
            {{false,false,false,false,false,false,false,false}, {false,true,false,false,false,false,false,true}, {false,true,true,true,true,true,true,true}, {false,true,false,false,false,false,false,true}, {false,false,false,false,false,false,false,false},{false,false,false,false,false,false,false,false}},// I
            {{false,false,true,false,false,false,false,false}, {false,true,false,false,false,false,false,false}, {false,true,false,false,false,false,false,true}, {false,false,true,true,true,true,true,true}, {false,false,false,false,false,false,false,true},{false,false,false,false,false,false,false,false}},// J
            {{false,true,true,true,true,true,true,true}, {false,false,false,false,true,false,false,false}, {false,false,false,true,false,true,false,false}, {false,false,true,false,false,false,true,false}, {false,true,false,false,false,false,false,true},{false,false,false,false,false,false,false,false}},// K
            {{false,true,true,true,true,true,true,true}, {false,true,false,false,false,false,false,false}, {false,true,false,false,false,false,false,false}, {false,true,false,false,false,false,false,false}, {false,true,false,false,false,false,false,false},{false,false,false,false,false,false,false,false}},// L
            {{false,true,true,true,true,true,true,true}, {false,false,false,false,false,false,true,false}, {false,false,false,false,false,true,false,false}, {false,false,false,false,false,false,true,false}, {false,true,true,true,true,true,true,true},{false,false,false,false,false,false,false,false}},// M
            {{false,true,true,true,true,true,true,true}, {false,false,false,false,false,true,false,false}, {false,false,false,false,true,false,false,false}, {false,false,false,true,false,false,false,false}, {false,true,true,true,true,true,true,true},{false,false,false,false,false,false,false,false}},// N
            {{false,false,true,true,true,true,true,false}, {false,true,false,false,false,false,false,true}, {false,true,false,false,false,false,false,true}, {false,true,false,false,false,false,false,true}, {false,false,true,true,true,true,true,false},{false,false,false,false,false,false,false,false}},// O
            {{false,true,true,true,true,true,true,true}, {false,false,false,false,true,false,false,true}, {false,false,false,false,true,false,false,true}, {false,false,false,false,true,false,false,true}, {false,false,false,false,false,true,true,false},{false,false,false,false,false,false,false,false}},// P
            {{false,false,true,true,true,true,true,false}, {false,true,false,false,false,false,false,true}, {false,true,false,true,false,false,false,true}, {false,false,true,false,false,false,false,true}, {false,true,false,true,true,true,true,false},{false,false,false,false,false,false,false,false}},// Q
            {{false,true,true,true,true,true,true,true}, {false,false,false,false,true,false,false,true}, {false,false,false,true,true,false,false,true}, {false,false,true,false,true,false,false,true}, {false,true,false,false,false,true,true,false},{false,false,false,false,false,false,false,false}},// R
            {{false,true,false,false,false,true,true,false}, {false,true,false,false,true,false,false,true}, {false,true,false,false,true,false,false,true}, {false,true,false,false,true,false,false,true}, {false,false,true,true,false,false,false,true},{false,false,false,false,false,false,false,false}},// S
            {{false,false,false,false,false,false,false,true}, {false,false,false,false,false,false,false,true}, {false,true,true,true,true,true,true,true}, {false,false,false,false,false,false,false,true}, {false,false,false,false,false,false,false,true},{false,false,false,false,false,false,false,false}},// T
            {{false,false,true,true,true,true,true,true}, {false,true,false,false,false,false,false,false}, {false,true,false,false,false,false,false,false}, {false,true,false,false,false,false,false,false}, {false,false,true,true,true,true,true,true},{false,false,false,false,false,false,false,false}},// U
            {{false,false,false,true,true,true,true,true}, {false,false,true,false,false,false,false,false}, {false,true,false,false,false,false,false,false}, {false,false,true,false,false,false,false,false}, {false,false,false,true,true,true,true,true},{false,false,false,false,false,false,false,false}},// V
            {{false,true,true,true,true,true,true,true}, {false,false,true,false,false,false,false,false}, {false,false,false,true,true,false,false,false}, {false,false,true,false,false,false,false,false}, {false,true,true,true,true,true,true,true},{false,false,false,false,false,false,false,false}},// W
            {{false,true,true,false,false,false,true,true}, {false,false,false,true,false,true,false,false}, {false,false,false,false,true,false,false,false}, {false,false,false,true,false,true,false,false}, {false,true,true,false,false,false,true,true},{false,false,false,false,false,false,false,false}},// X
            {{false,false,false,false,false,false,true,true}, {false,false,false,false,false,true,false,false}, {false,true,true,true,true,false,false,false}, {false,false,false,false,false,true,false,false}, {false,false,false,false,false,false,true,true},{false,false,false,false,false,false,false,false}},// Y
            {{false,true,true,false,false,false,false,true}, {false,true,false,true,false,false,false,true}, {false,true,false,false,true,false,false,true}, {false,true,false,false,false,true,false,true}, {false,true,false,false,false,false,true,true},{false,false,false,false,false,false,false,false}},// Z
            {{false,false,false,false,false,false,false,false}, {false,false,false,false,false,false,false,false}, {false,true,true,true,true,true,true,true}, {false,true,false,false,false,false,false,true}, {false,true,false,false,false,false,false,true},{false,false,false,false,false,false,false,false}},// [
            {{false,false,false,false,false,false,true,false}, {false,false,false,false,false,true,false,false}, {false,false,false,false,true,false,false,false}, {false,false,false,true,false,false,false,false}, {false,false,true,false,false,false,false,false},{false,false,false,false,false,false,false,false}},// "\"
            {{false,true,false,false,false,false,false,true}, {false,true,false,false,false,false,false,true}, {false,true,true,true,true,true,true,true}, {false,false,false,false,false,false,false,false}, {false,false,false,false,false,false,false,false},{false,false,false,false,false,false,false,false}},// ]
            {{false,false,false,false,false,true,false,false}, {false,false,false,false,false,false,true,false}, {false,false,false,false,false,false,false,true}, {false,false,false,false,false,false,true,false}, {false,false,false,false,false,true,false,false},{false,false,false,false,false,false,false,false}},// ^
            {{false,true,false,false,false,false,false,false}, {false,true,false,false,false,false,false,false}, {false,true,false,false,false,false,false,false}, {false,true,false,false,false,false,false,false}, {false,true,false,false,false,false,false,false},{false,false,false,false,false,false,false,false}},// _
            {{false,false,false,false,false,false,false,false}, {false,false,false,false,false,false,false,true}, {false,false,false,false,false,false,true,false}, {false,false,false,false,false,true,false,false}, {false,false,false,false,false,false,false,false},{false,false,false,false,false,false,false,false}},// `
            {{false,false,true,false,false,false,false,false}, {false,true,false,true,false,true,false,false}, {false,true,false,true,false,true,false,false}, {false,true,false,true,false,true,false,false}, {false,true,true,true,true,false,false,false},{false,false,false,false,false,false,false,false}},// a
            {{false,true,true,true,true,true,true,true}, {false,true,false,false,true,false,false,false}, {false,true,false,false,false,true,false,false}, {false,true,false,false,false,true,false,false}, {false,false,true,true,true,false,false,false},{false,false,false,false,false,false,false,false}},// b
            {{false,false,true,true,true,false,false,false}, {false,true,false,false,false,true,false,false}, {false,true,false,false,false,true,false,false}, {false,true,false,false,false,true,false,false}, {false,false,true,false,false,false,false,false},{false,false,false,false,false,false,false,false}},// c
            {{false,false,true,true,true,false,false,false}, {false,true,false,false,false,true,false,false}, {false,true,false,false,false,true,false,false}, {false,true,false,false,true,false,false,false}, {false,true,true,true,true,true,true,true},{false,false,false,false,false,false,false,false}},// d
            {{false,false,true,true,true,false,false,false}, {false,true,false,true,false,true,false,false}, {false,true,false,true,false,true,false,false}, {false,true,false,true,false,true,false,false}, {false,false,false,true,true,false,false,false},{false,false,false,false,false,false,false,false}},// e
            {{false,false,false,false,true,false,false,false}, {false,true,true,true,true,true,true,false}, {false,false,false,false,true,false,false,true}, {false,false,false,false,false,false,false,true}, {false,false,false,false,false,false,true,false},{false,false,false,false,false,false,false,false}},// f
            {{false,false,false,false,true,false,false,false}, {false,false,false,true,false,true,false,false}, {false,true,false,true,false,true,false,false}, {false,true,false,true,false,true,false,false}, {false,false,true,true,true,true,false,false},{false,false,false,false,false,false,false,false}},// g
            {{false,true,true,true,true,true,true,true}, {false,false,false,false,true,false,false,false}, {false,false,false,false,false,true,false,false}, {false,false,false,false,false,true,false,false}, {false,true,true,true,true,false,false,false},{false,false,false,false,false,false,false,false}},// h
            {{false,false,false,false,false,false,false,false}, {false,true,false,false,false,true,false,false}, {false,true,true,true,true,true,false,true}, {false,true,false,false,false,false,false,false}, {false,false,false,false,false,false,false,false},{false,false,false,false,false,false,false,false}},// i
            {{false,false,true,false,false,false,false,false}, {false,true,false,false,false,false,false,false}, {false,true,false,false,false,true,false,false}, {false,false,true,true,true,true,false,true}, {false,false,false,false,false,false,false,false},{false,false,false,false,false,false,false,false}},// j
            {{false,false,false,false,false,false,false,false}, {false,true,true,true,true,true,true,true}, {false,false,false,true,false,false,false,false}, {false,false,true,false,true,false,false,false}, {false,true,false,false,false,true,false,false},{false,false,false,false,false,false,false,false}},// k
            {{false,false,false,false,false,false,false,false}, {false,true,false,false,false,false,false,true}, {false,true,true,true,true,true,true,true}, {false,true,false,false,false,false,false,false}, {false,false,false,false,false,false,false,false},{false,false,false,false,false,false,false,false}},// l
            {{false,true,true,true,true,true,false,false}, {false,false,false,false,false,true,false,false}, {false,false,false,true,true,false,false,false}, {false,false,false,false,false,true,false,false}, {false,true,true,true,true,false,false,false},{false,false,false,false,false,false,false,false}},// m
            {{false,true,true,true,true,true,false,false}, {false,false,false,false,true,false,false,false}, {false,false,false,false,false,true,false,false}, {false,false,false,false,false,true,false,false}, {false,true,true,true,true,false,false,false},{false,false,false,false,false,false,false,false}},// n
            {{false,false,true,true,true,false,false,false}, {false,true,false,false,false,true,false,false}, {false,true,false,false,false,true,false,false}, {false,true,false,false,false,true,false,false}, {false,false,true,true,true,false,false,false},{false,false,false,false,false,false,false,false}},// o
            {{false,true,true,true,true,true,false,false}, {false,false,false,true,false,true,false,false}, {false,false,false,true,false,true,false,false}, {false,false,false,true,false,true,false,false}, {false,false,false,false,true,false,false,false},{false,false,false,false,false,false,false,false}},// p
            {{false,false,false,false,true,false,false,false}, {false,false,false,true,false,true,false,false}, {false,false,false,true,false,true,false,false}, {false,false,false,true,true,false,false,false}, {false,true,true,true,true,true,false,false},{false,false,false,false,false,false,false,false}},// q
            {{false,true,true,true,true,true,false,false}, {false,false,false,false,true,false,false,false}, {false,false,false,false,false,true,false,false}, {false,false,false,false,false,true,false,false}, {false,false,false,false,true,false,false,false},{false,false,false,false,false,false,false,false}},// r
            {{false,true,false,false,true,false,false,false}, {false,true,false,true,false,true,false,false}, {false,true,false,true,false,true,false,false}, {false,true,false,true,false,true,false,false}, {false,false,true,false,false,false,false,false},{false,false,false,false,false,false,false,false}},// s
            {{false,false,false,false,false,true,false,false}, {false,false,true,true,true,true,true,true}, {false,true,false,false,false,true,false,false}, {false,true,false,false,false,false,false,false}, {false,false,true,false,false,false,false,false},{false,false,false,false,false,false,false,false}},// t
            {{false,false,true,true,true,true,false,false}, {false,true,false,false,false,false,false,false}, {false,true,false,false,false,false,false,false}, {false,false,true,false,false,false,false,false}, {false,true,true,true,true,true,false,false},{false,false,false,false,false,false,false,false}},// u
            {{false,false,false,true,true,true,false,false}, {false,false,true,false,false,false,false,false}, {false,true,false,false,false,false,false,false}, {false,false,true,false,false,false,false,false}, {false,false,false,true,true,true,false,false},{false,false,false,false,false,false,false,false}},// v
            {{false,false,true,true,true,true,false,false}, {false,true,false,false,false,false,false,false}, {false,false,true,true,false,false,false,false}, {false,true,false,false,false,false,false,false}, {false,false,true,true,true,true,false,false},{false,false,false,false,false,false,false,false}},// w
            {{false,true,false,false,false,true,false,false}, {false,false,true,false,true,false,false,false}, {false,false,false,true,false,false,false,false}, {false,false,true,false,true,false,false,false}, {false,true,false,false,false,true,false,false},{false,false,false,false,false,false,false,false}},// x
            {{false,false,false,false,true,true,false,false}, {false,true,false,true,false,false,false,false}, {false,true,false,true,false,false,false,false}, {false,true,false,true,false,false,false,false}, {false,false,true,true,true,true,false,false},{false,false,false,false,false,false,false,false}},// y
            {{false,true,false,false,false,true,false,false}, {false,true,true,false,false,true,false,false}, {false,true,false,true,false,true,false,false}, {false,true,false,false,true,true,false,false}, {false,true,false,false,false,true,false,false},{false,false,false,false,false,false,false,false}},// z
            {{false,false,false,false,false,false,false,false}, {false,false,false,false,true,false,false,false}, {false,false,true,true,false,true,true,false}, {false,true,false,false,false,false,false,true}, {false,false,false,false,false,false,false,false},{false,false,false,false,false,false,false,false}},// {
            {{false,false,false,false,false,false,false,false}, {false,false,false,false,false,false,false,false}, {false,true,true,true,true,true,true,true}, {false,false,false,false,false,false,false,false}, {false,false,false,false,false,false,false,false},{false,false,false,false,false,false,false,false}},// |
            {{false,false,false,false,false,false,false,false}, {false,true,false,false,false,false,false,true}, {false,false,true,true,false,true,true,false}, {false,false,false,false,true,false,false,false}, {false,false,false,false,false,false,false,false},{false,false,false,false,false,false,false,false}},// }
            {{false,false,false,true,false,false,false,false}, {false,false,false,false,false,true,false,false}, {false,false,false,false,true,false,false,false}, {false,false,false,true,false,false,false,false},{false,false,false,false,true,false,false,false}, {false,false,false,false,false,false,false,false}},// ~
            {{false,false,false,false,true,false,false,false}, {false,false,false,true,true,true,false,false}, {false,false,true,false,true,false,true,false}, {false,false,false,false,true,false,false,false}, {false,false,false,false,true,false,false,false},{false,false,false,false,false,false,false,false}} // <-
    };



    public boolean[][] setScrollText(String text, final int charIdx, int scrollColNum, int charScrollRemainingTime, int scrollPeriod,byte ledFontIdentifier){

        globali=0;
        int speed = 0;
        int i,  ShiftAmount = 0, scroll = 0, temp = 0, shift_step=1, StringLength,FullStringLength;
        String message=text.substring(charIdx,text.length());
        char index = 0;
        StringLength=message.length();
        FullStringLength=text.length();
        scrollLength=message.length()*26;
        FullScrollLength = text.length()*6;
        messageBuffer= new boolean[scrollLength][7];
        FullMessageBuffer = new boolean[FullScrollLength][7];
        boolean isFirstChar=true;
        boolean tempChar[][]= new boolean[6][8];
        Integer curPos=0;

        for (i=0;i<FullStringLength;i++){
            index= text.toCharArray()[i];
            if(ledFontIdentifier == 0x55)
           {
               tempChar = lookup55[index-32];
           }
           else if(ledFontIdentifier == 0x57)
            {
                tempChar = lookup57[index - 32];
            }else {

                tempChar = lookup57[index - 32];
            }

            boolean transpose [][]= new boolean[8][6];
            for (int j=0;j<6;j++){
                for (int k=0;k<8;k++){
                    transpose[k][j]=tempChar[j][k];
                }
            }

            for(int k=0;k<6;k++){
                for (int j=1;j<8;j++){
                    FullMessageBuffer[curPos][j-1]=transpose[j][k];

                }
                curPos++;
            }
    }

        globali = (charIdx*6) + scrollColNum;

        for (int j=0;j<25;j++){

            if(globali >= FullScrollLength)
            {
                globali = 0;
            }

            DisplayBuffer[j]=FullMessageBuffer[globali];
            globali++;

        }



/*        if(globali<FullScrollLength) {
            for (int j=0;j<24;j++){
                DisplayBuffer[j]=DisplayBuffer[j+1];
            }
            DisplayBuffer[24]=FullMessageBuffer[globali];
            globali++;
            isFirstTime=false;
            return DisplayBuffer;
        }
        else
        {
            globali = 0;

        }*/
        return DisplayBuffer;


    }

}
